# Generated by Django 3.2 on 2025-08-21 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecochallengereward',
            name='awarded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rewards_awarded', to=settings.AUTH_USER_MODEL, verbose_name='Attribuée par'),
        ),
        migrations.AddField(
            model_name='ecochallengereward',
            name='challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='users.ecochallenge'),
        ),
        migrations.AddField(
            model_name='ecochallengereward',
            name='claimed',
            field=models.BooleanField(default=False, verbose_name='Réclamée'),
        ),
        migrations.AddField(
            model_name='ecochallengereward',
            name='claimed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Réclamée le'),
        ),
        migrations.AddField(
            model_name='ecochallengereward',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='ecochallengereward',
            name='points',
            field=models.PositiveIntegerField(default=0, verbose_name='Points'),
        ),
        migrations.AddField(
            model_name='ecochallengereward',
            name='reward_type',
            field=models.CharField(choices=[('points', 'Points'), ('badge', 'Badge'), ('discount', 'Réduction'), ('free_rental', 'Location gratuite'), ('certificate', 'Certificat'), ('eco_bonus', 'Bonus écologique')], default='points', max_length=20, verbose_name='Type de récompense'),
        ),
        migrations.AddField(
            model_name='ecochallengereward',
            name='title',
            field=models.CharField(default='Récompense', max_length=200, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='ecochallengereward',
            name='user_challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='users.userecochallenge'),
        ),
    ]
