# Generated by Django 5.2.4 on 2025-07-19 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agence',
            options={'ordering': ['-date_creation']},
        ),
     
       
        migrations.RemoveIndex(
            model_name='reservation',
            name='reservation_user_idx',
        ),
        migrations.RemoveIndex(
            model_name='reservation',
            name='reservation_vehicule_idx',
        ),
        migrations.RemoveIndex(
            model_name='vehicule',
            name='vehicule_agence_idx',
        ),
        migrations.RenameField(
            model_name='agence',
            old_name='created_at',
            new_name='date_creation',
        ),
        migrations.RemoveField(
            model_name='agence',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='vehicule_id',
        ),
        migrations.RemoveField(
            model_name='vehicule',
            name='agence_id',
        ),
        migrations.AddField(
            model_name='agence',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='agence',
            name='site_web',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservation',
            name='vehicule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.vehicule'),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='agence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicules', to='users.agence'),
        ),
        migrations.AlterField(
            model_name='agence',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agence',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='immatriculation',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddIndex(
            model_name='agence',
            index=models.Index(fields=['email'], name='agence_email_idx'),
        ),
        migrations.AddIndex(
            model_name='agence',
            index=models.Index(fields=['date_creation'], name='agence_date_creation_idx'),
        ),
        migrations.AddIndex(
            model_name='agence',
            index=models.Index(fields=['code_postal'], name='agence_code_postal_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['user'], name='reservation_user_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['vehicule'], name='reservation_vehicule_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicule',
            index=models.Index(fields=['agence'], name='vehicule_agence_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicule',
            index=models.Index(fields=['immatriculation'], name='vehicule_immatriculation_idx'),
        ),
    ]
