# Generated by Django 3.2 on 2025-07-19 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_agence_options_remove_agence_agence_pays_idx_and_more'),
        ('users', '0003_alter_user_managers'),
    ]

    operations = [
    ]
