# Generated by Django 3.2 on 2025-07-20 14:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_merge_20250719_2136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agence',
            options={},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='vehicule',
            options={},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveIndex(
            model_name='agence',
            name='agence_pays_idx',
        ),
        migrations.RemoveIndex(
            model_name='agence',
            name='agence_created_at_idx',
        ),
        migrations.RemoveIndex(
            model_name='agence',
            name='agence_email_idx',
        ),
        migrations.RemoveIndex(
            model_name='agence',
            name='agence_code_postal_idx',
        ),
        migrations.RemoveIndex(
            model_name='reservation',
            name='reservation_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='vehicule',
            name='vehicule_marque_modele_idx',
        ),
        migrations.RemoveIndex(
            model_name='vehicule',
            name='vehicule_carburant_idx',
        ),
        migrations.RemoveIndex(
            model_name='vehicule',
            name='vehicule_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='vehicule',
            name='vehicule_prix_idx',
        ),
        migrations.RemoveIndex(
            model_name='vehicule',
            name='vehicule_immatriculation_idx',
        ),
        migrations.AddField(
            model_name='user',
            name='email_verification_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='password_reset_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password_reset_token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agence',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='agence',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='agence',
            name='site_web',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='agence',
            name='telephone',
            field=models.CharField(blank=True, default='', max_length=20, validators=[django.core.validators.RegexValidator(message='Le numéro de téléphone doit contenir au moins 8 chiffres.', regex='^\\+?\\d{8,}$')]),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='commentaires',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='montant_total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('confirmee', 'Confirmée'), ('annulee', 'Annulée'), ('terminee', 'Terminée')], default='en_attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='vehicule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='users.vehicule'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=models.CharField(blank=True, default='', max_length=20, validators=[django.core.validators.RegexValidator(message='Le numéro de téléphone doit contenir au moins 8 chiffres.', regex='^\\+?\\d{8,}$')]),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='agence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicules', to='users.agence'),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='annee',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='carburant',
            field=models.CharField(choices=[('électrique', 'Électrique'), ('hybride', 'Hybride'), ('essence', 'Essence'), ('diesel', 'Diesel')], default='essence', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='consommationEnergie',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='couleur',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='date_derniere_maintenance',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='emissionsCO2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle_images/'),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='immatriculation',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='kilometrage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='localisation',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='marque',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='modele',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='prix_par_jour',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='prochaine_maintenance',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email_verification_token'], name='user_email_verification_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['password_reset_token'], name='user_password_reset_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicule',
            index=models.Index(fields=['marque'], name='vehicule_marque_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicule',
            index=models.Index(fields=['modele'], name='vehicule_modele_idx'),
        ),
    ]
