# Generated by Django 3.2 on 2025-07-20 15:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20250720_1558'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agence',
            options={'ordering': ['-date_creation']},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='vehicule',
            options={'ordering': ['-created_at']},
        ),
        # Les suppressions d'index sont commentées car non supportées par Djongo
        # migrations.RemoveIndex(
        #     model_name='user',
        #     name='user_email_verification_idx',
        # ),
        # migrations.RemoveIndex(
        #     model_name='user',
        #     name='user_password_reset_idx',
        # ),
        # migrations.RemoveIndex(
        #     model_name='vehicule',
        #     name='vehicule_marque_idx',
        # ),
        # migrations.RemoveIndex(
        #     model_name='vehicule',
        #     name='vehicule_modele_idx',
        # ),
        # migrations.RemoveField(
        #     model_name='user',
        #     name='password_reset_token_expiry',
        # ),
        migrations.AddField(
            model_name='user',
            name='password_reset_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agence',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agence',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='agence',
            name='site_web',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agence',
            name='telephone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='commentaires',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='montant_total',
            field=models.DecimalField(decimal_places=2, help_text='Montant total en euros', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('confirmee', 'Confirmée'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='en_attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='vehicule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.vehicule'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_verification_token',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password_reset_token',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='agence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicules', to='users.agence'),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='annee',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='carburant',
            field=models.CharField(choices=[('électrique', 'Électrique'), ('hybride', 'Hybride'), ('essence', 'Essence'), ('diesel', 'Diesel')], max_length=20),
        ),
        # ATTENTION : cette opération n'est pas supportée par Djongo, donc on la commente
        # migrations.AlterField(
        #     model_name='vehicule',
        #     name='consommationEnergie',
        #     field=models.DecimalField(blank=True, decimal_places=2, help_text='Consommation en L/100km ou kWh/100km', max_digits=5, null=True),
        # ),
        migrations.AlterField(
            model_name='vehicule',
            name='couleur',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='date_derniere_maintenance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='description',
            field=models.TextField(blank=True),
        ),
        # ATTENTION : cette opération n'est pas supportée par Djongo, donc on la commente
        # migrations.AlterField(
        #     model_name='vehicule',
        #     name='emissionsCO2',
        #     field=models.IntegerField(blank=True, help_text='Émissions CO2 en g/km', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        # ),
        migrations.AlterField(
            model_name='vehicule',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='vehicules/'),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='immatriculation',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='kilometrage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='localisation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='marque',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='modele',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='prix_par_jour',
            field=models.DecimalField(decimal_places=2, help_text='Prix quotidien en euros', max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='prochaine_maintenance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='agence',
            index=models.Index(fields=['email'], name='agence_email_idx'),
        ),
        migrations.AddIndex(
            model_name='agence',
            index=models.Index(fields=['code_postal'], name='agence_code_postal_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['date_debut', 'date_fin'], name='reservation_date_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicule',
            index=models.Index(fields=['marque', 'modele'], name='vehicule_marque_modele_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicule',
            index=models.Index(fields=['carburant'], name='vehicule_carburant_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicule',
            index=models.Index(fields=['type'], name='vehicule_type_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicule',
            index=models.Index(fields=['prix_par_jour'], name='vehicule_prix_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicule',
            index=models.Index(fields=['immatriculation'], name='vehicule_immatriculation_idx'),
        ),
    ]