# Generated by Django 3.2 on 2025-07-20 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20250720_1639'),
    ]

   # operations = [
       # migrations.RemoveIndex(
        #    model_name='reservation',
        #    name='reservation_user_idx',
      #  ),
   # ]
