# Generated by Django 3.2 on 2025-07-21 23:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_reservation_reservation_user_idx'),
    ]

    operations = [
       
    ]
